<?php
/**
 * @var $block \Mirasvit\Brand\Block\AllBrand
 */
?>
<?php
    $collection = $block->getBrandsByLetters();
?>
<div class="brand">
    <div class="filter">
        <div class="all-brand">
            <a href="javascript:void(0)" class="letter-all-brand brand-filter-link"><?= __('All brands') ?></a>
        </div>
        <div class="letter">
            <?php foreach ($collection as $letter => $brands): ?>
                <a href="javascript:void(0)"
                   class="letter-<?= /* @escapeNotVerified */ $letter ?> brand-filter-link">
                    <?= /* @escapeNotVerified */ $letter ?>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="brand-options">
        <?php foreach ($collection as $letter => $brands): ?>
            <div class="brand-letter-<?= /* @escapeNotVerified */ $letter ?> brand-row">
                <div class="brand-letter"><?= /* @escapeNotVerified */ $letter ?></div>
                <ul>
                    <?php /** @var \Mirasvit\Brand\Api\Data\BrandInterface $brand */ ?>
                    <?php foreach ($brands as $brand): ?>
                        <li>
                            <a href="<?= /* @escapeNotVerified */ $brand->getUrl() ?>">
                                <?php if($block->canShowImage($brand)): ?>
                                    <div class="m__all_brand_image_wrapper">
                                        <img class="m__all_brand_image" src="<?= /* @escapeNotVerified */ $brand->getImage() ?>">
                                    </div>
                                <?php endif; ?>
                                <div class="m__all_brand_label"><?= /* @escapeNotVerified */ $brand->getLabel() ?></div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/x-magento-init">
{
    ".<?php echo 'brand-filter-link'; ?>": {
        "Mirasvit_Brand/js/mBrandFilter": {}
    }
}
</script>
