<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\State
 */

$_filters = $block->getActiveFilters();
$isAjaxEnabled = $block->isAjaxEnabled();
?>
<?php if (!empty($_filters)): ?>
    <div class="filter-current" id="<?= \Mirasvit\LayeredNavigation\Api\Config\ConfigInterface::AJAX_STATE_WRAPPER_ID ?>"
         data-mage-init='{"collapsible":{"active": false, "openedState": "active", "collapsible": true}}'>
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                data-role="title"
                aria-level="2"
                data-count="<?= count($_filters) ?>"><?= /* @escapeNotVerified */ __('Now Shopping by') ?></strong>
        <ol class="items">
            <?php foreach ($_filters as $_filter): ?>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                ?>
                <li class="item <?= \Mirasvit\LayeredNavigation\Api\Config\ConfigInterface::AJAX_STATE_WRAPPER_CLASS ?>"
                    data-container="<?= /* @escapeNotVerified */ $_filter->getFilter()->getRequestVar() ?>"
                    data-value="<?= /* @escapeNotVerified */ $block->getPreparedValue($_filter->getFilter()->getRequestVar(),
                        $block->escapeHtml($_filter->getValueString(), false));  ?>">
                        <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                        <span class="filter-value"><?= /* @escapeNotVerified */ $block->stripTags($_filter->getLabel()) ?></span>
                        <?php if ($clearLinkUrl): ?>
                            <a class="action previous" href="<?= /* @escapeNotVerified */ $_filter->getRemoveUrl() ?>"
                               title="<?= /* @escapeNotVerified */ __('Previous') ?>">
                                <span><?= /* @escapeNotVerified */ __('Previous') ?></span>
                            </a>
                            <a class="action remove"
                               title="<?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                               href="<?= /* @escapeNotVerified */ $clearLinkUrl ?>">
                                <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                            </a>
                        <?php else: ?>
                            <a class="action remove" href="<?= /* @escapeNotVerified */ $_filter->getRemoveUrl() ?>"
                               title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Remove')) . " " . $currentFilterName ?>">
                                <span><?= /* @escapeNotVerified */ __('Remove This Item') ?></span>
                            </a>
                        <?php endif; ?>
                </li>
            <input class="<?= \Mirasvit\LayeredNavigation\Api\Config\ConfigInterface::AJAX_STATE_WRAPPER_INPUT_CLASS ?>"
                    name="<?php echo /* @escapeNotVerified */ $_filter->getFilter()->getRequestVar() ?>"
                    value="<?= /* @escapeNotVerified */ $block->getPreparedValue($_filter->getFilter()->getRequestVar(),
                        $block->escapeHtml($_filter->getValueString(), false)); ?>"
                    type="checkbox"
                    style="display: none;"
                    <?php echo 'checked' ?>
                />
            <?php endforeach; ?>
            <?php if ($block->isHorizontalFilter()): ?>
            <li class="block-actions filter-actions" style="display: inline-block;">
                <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
            </li>
            <?php endif; ?>
        </ol>

        <?php if ($isAjaxEnabled): ?>
            <script type="text/x-magento-init">
            {
                "#<?= \Mirasvit\LayeredNavigation\Api\Config\ConfigInterface::AJAX_STATE_WRAPPER_ID ?>": {
                    "Mirasvit_LayeredNavigation/js/navigation/state": {
                        "filtersWrapperSelector": ".<?= \Mirasvit\LayeredNavigation\Api\Config\ConfigInterface::AJAX_STATE_WRAPPER_CLASS ?>",
                        "cleanAllUrl": "<?= $block->getClearUrl() ?>"
                    }
                }
            }
            </script>
        <?php endif; ?>
    </div>
<?php endif; ?>
