<div id="<?php /* @escapeNotVerified */ echo $htmlId;?>-container" class="images"
     data-max-file-size="<?php /* @escapeNotVerified */ echo $fileMaxSize;?>"
    >
    <div class="image image-placeholder">
        <input class="m__navigation_input"
               type="file"
               name="image"
               data-url="<?php /* @escapeNotVerified */ echo $uploadUrl;?>"
               multiple="multiple" />
        <img class="spacer" src="<?php /* @escapeNotVerified */ echo $spacerImage;?>"/>
        <p class="image-placeholder-text"><?php /* @escapeNotVerified */ echo $imagePlaceholderText;?></p>
    </div>
    <script
        id="<?php /* @escapeNotVerified */ echo $htmlId;?>-template"
        data-template="image"
        type="text/x-magento-template">
        <div class="image">
            <img class="spacer" src="<?php /* @escapeNotVerified */ echo $spacerImage;?>"/>
            <img
                class="product-image"
                src="<%- data.url %>"
                data-position="<%- data.position %>"
                alt="<%- data.label %>" />
            <div class="actions">
                <button
                    type="button"
                    class="action-delete"
                    data-role="delete-button"
                    title="<?php /* @escapeNotVerified */ echo $deleteImageText;?>">
                    <span><?php /* @escapeNotVerified */ echo $deleteImageText;?></span>
                </button>
            </div>
            <div class="image-fade"><span><?php /* @escapeNotVerified */ echo $hiddenText;?></span></div>
        </div>
    </script>
</div>