<?php
    /* @var $block \Mirasvit\Brand\Block\Logo */
?>
<?php
    $brandUrl = $this->getBrandUrl();
    $title = $this->getTitle();
    $logoImageUrl = $block->getLogoImageUrl();
    $imageWidth = $block->getImageWidth();
    $tooltipContent = $block->getTooltipContent();
    $isProductPage = $block->isProductPage();
?>
<div class="m-logo">
    <a class="m-brand-tooltip" href="/<?= /* @escapeNotVerified */ $brandUrl ?>"
       data-m-tooltip-content='<?= /* @escapeNotVerified */ $tooltipContent ?>'
    >
        <img style="width: <?= /* @escapeNotVerified */ $imageWidth ?>px;"
            title="<?= /* @escapeNotVerified */ $title; ?>"
            alt="<?= /* @escapeNotVerified */ $title; ?>"
            src="<?= /* @escapeNotVerified */ $logoImageUrl ?>"
        />
    </a>
    <?php if ($isProductPage): ?>
        <span><?= /* @escapeNotVerified */ $block->getBrandDescription(); ?></span>
    <?php endif; ?>
</div>
<script>
    require([
        'jquery',
        "mage/tooltip"
    ], function ($) {
        $('.m-brand-tooltip').tooltip({
            position: {
                my: "left-15 bottom-10",
                at: "center top",
                collision: "flip flip",
                using: function( position, feedback ) {
                    $( this ).addClass( feedback.vertical )
                        .css( position );
                    var windowWidth = $( window ).width();
                    var elementWidth = feedback.target.left + feedback.element.width;
                    if (feedback.horizontal == 'right'
                        || (feedback.horizontal == 'left' && elementWidth > windowWidth)) {
                        $('.m-brand-tooltip-container .ui-tooltip-content').append(
                            '<style>' +
                                '.m-brand-tooltip-container .ui-tooltip-content::before,' +
                                '.m-brand-tooltip-container .ui-tooltip-content::after {' +
                                    'right: 5px !important;' +
                                    'left: auto !important;' +
                                '}' +
                            '</style>'
                        );
                    }
                }
            },
            tooltipClass: "m-brand-tooltip-container",
            content: function () {
                return $(this).parent().data('mTooltipContent');
            }
        });
    });


</script>
